fix: remove inline comments from .flake8 config
Flake8 doesn't support inline comments in the ignore list.
This was causing CI to fail with:
ValueError: Error code '#' supplied to 'ignore' option

Removed comments to fix the issue.